### ISSUE TITLE
[Request] Add "Active Mode" to build initial database

### ISSUE THREAD

**Issue by TripodKnight** [n76/DejaVu#25]
Current functionality: 

DejaVu requires another app to request GPS location in order for database to begin being built (eg: Maps.me)

Desired functionality:

A toggle is made in DejaVu to actively build a database by requesting GPS on its own. Ideally this would be ran by the user for the first while in a new location to build new database entries.

I'm sure this would be a drain on battery however its implemented. Is this possible, or is this beyond the scope of this project? Thank you very much for this backend!

**Comment by n76** [comment]
I have been thinking about this request and have decided that it is out of scope. My reasoning is pretty much the same as @gdt lists.

The other one is that I can come up with scenarios where turning on the GPS when you have RF signals that you can't identify will not work which means that a control panel would be needed to enable/disable the feather. Since I am trying to avoid having a control panel (the goal is to make it "just work") that is another reason to avoid implementing this.

**Comment by Lee-Carre** [comment]
There are apps which have a feature to toggle GNSS on (and keep it enabled), without doing much more (low memory usage).
* [OpenTracks](//www.f-droid.org/packages/de.dennisguse.opentracks) (`Start G[NS]S`, which is distinct from starting to record a track)
* [My Location](//www.f-droid.org/packages/com.mirfatif.mylocation) (`Lock G[NS]S`) (has other useful features, including the ability to query UnifiedNLP backends)

I use such an app when I'm out, for a whole variety of reasons (besides for n76's backends to collect data, also other data-collectors (e.g. Tower Collector), [map](//www.openstreetmap.org/) surveying, and not having to wait for GNSS to stabilise when I want to use various (e.g. navigation) apps).

However, I also use an external battery, so the extra power usage isn't a concern for me. It might be for others.
